[package]
name = "Ferris"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = "0.12.5"
tokio = { version = "1.38.0", features = ["full"] }
providers = { path = "src/providers" }
regex = "1.5.4"
