[package]
name = "providers"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = "0.12.5"
tokio = { version = "1.38.0", features = ["full"] }
select = "0.6.0"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
regex = "1.5.4"
strsim = "0.10"
anyhow = "1.0.91"
